import { StyleSheet } from "react-native";


const styles = StyleSheet.create({
    container: {
      flex: 1,
      alignItems: 'center',
      backgroundColor: '#F5FCFF',
      margin: 10,
      borderRadius: 10,
      elevation: 5,
    },
    background: {
      flex: 1,
      resizeMode: "cover",
      backgroundColor: '#F5FCFF',
      width: '100%',
      height: '100%',
    },
    buttonContainer: {
      flex: 1,
      alignItems: 'center',
      alignContent: 'center',
      marginTop: 5,
      marginLeft: 20,
      marginRight: 20,
    },
    TextBienvenida: {
      flexDirection: 'column',
      alignItems: 'flex-start',
      alignContent: 'flex-start',
      margin: 10,
    },
    Title: {
      fontSize: 25,
      fontWeight: 'bold',
      color: 'gray', 
      marginTop: 5,   
    },
    parraf: {
      fontSize: 15,
      color: 'gray',
      textAlign: 'justify',
      margin: 10,
    },
    row: {
      flexDirection: 'row',
      top: 10,
    },
    button1: {
      flex: 1,
      flexDirection: 'column', 
      alignContent: 'center',
      height: 200,
      margin: 7,
      backgroundColor: '#57D400',
      justifyContent: 'center',
      alignItems: 'center',
      borderBottomRightRadius: 90, 
      borderRadius: 10,   
    },
    button2: {
      flex: 1,
      flexDirection: 'column', 
      alignContent: 'center',
      height: 200,
      margin: 7,
      backgroundColor: '#009881',
      justifyContent: 'center',
      alignItems: 'center',
      borderBottomLeftRadius: 90, 
      borderRadius: 10,   
    },
    button3: {
      flex: 1,
      flexDirection: 'column', 
      alignContent: 'center',
      height: 200,
      margin: 7,
      backgroundColor: '#FFB029',
      justifyContent: 'center',
      alignItems: 'center',
      borderTopRightRadius: 90,
      borderRadius: 10,    
    },
    button4: {
      flex: 1,
      flexDirection: 'column', 
      alignContent: 'center',
      height: 200,
      margin: 7,
      backgroundColor: '#FF1926',
      justifyContent: 'center',
      alignItems: 'center',
      borderTopLeftRadius: 90,
      borderRadius: 10,
    },
    buttonText: {
      color: 'white',
      fontSize: 20,
      fontWeight: 'bold',
      alignSelf: 'center',
      justifyContent: 'center',
      alignContent: 'center',
      textAlign: 'center',
    },
    logo: {
      height: 90,
      resizeMode: 'contain',
      alignContent: 'center',
      justifyContent: 'center',
      alignSelf: 'center',
      margin: -50,
    },
    logos: {
      height: 90,
      width: 90,
      resizeMode: 'contain',
      alignContent: 'center',
      justifyContent: 'center',
      alignSelf: 'center',
    },
  
  });

  export default styles;