import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    container: {
        justifyContent: 'center',
        flexDirection: 'column',
        width: '100%',
        height: '100%',
        backgroundColor: '#ffffff',
    },
    image: {
        width: 50,
        height: 50,
        resizeMode: 'contain',
        marginTop: 10,
    },
    header: {
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#007881',
        width: '100%',
        borderRadius: 10,
        padding: 10,
        marginTop: 5,
    },
    title: {
        fontSize: 20,
        fontWeight: 'bold',
        color: 'white',
        margin: 1,
    },
    events: {
        alignItems: 'center',
        justifyContent: 'center',
        marginLeft: 5,
        marginRight: 5,
        marginTop: 5,
    },
    eventsTitle: {
        fontSize: 15,
        fontWeight: 'bold',
        color: 'black',
        marginTop: 5,
    },
    eventsContainer: {
        alignItems: 'center',
        padding: 7,
        justifyContent: 'center',
        borderRadius: 10,
        backgroundColor: '#ffffff', // Cambia al color deseado
    },
    MenuButtons: {
        flexDirection: 'row',
        justifyContent: 'space-evenly',
        alignItems: 'center',
        width: '100%',
        backgroundColor: '#fff',
        marginBottom: 10,
    },
    button: {
        backgroundColor: '#57D400',
        width: 85,
        height: 30,
        borderRadius: 20,
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 10,
        left: 1,
    },
    button2: {
        backgroundColor: '#009881',
        width: 85,
        height: 30,
        borderRadius: 20,
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 10,
        left: 1,
    },
    button3: {
        backgroundColor: '#FFB029',
        width: 85,
        height: 30,
        borderRadius: 20,
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 10,
        left: 1,
    },
    button4: {
        backgroundColor: '#FF1926',
        width: 85,
        height: 30,
        borderRadius: 20,
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 10,
        left: 1,
    },
    buttonText: {
        fontSize: 12,
        fontWeight: 'bold',
        color: 'white',
        justifyContent: 'center',
        alignItems: 'center',
        textAlign: 'center',
    },
    titleBar: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignContent: "center",
        alignItems: "center",
        alignSelf: 'stretch',
        paddingHorizontal: 16,
        paddingTop: 40,
    },
    logo: {
        width: 25,
        height: 25,
        resizeMode: "contain",
    },
    logos: {
        width: 40,
        height: 40,
        resizeMode: "contain",
    },
    arrow: {
        width: 30, // Tamaño de la flecha
        height: 30,
    },
});

export default styles;